/**
 * Zoho Creator .ds file emitter.
 *
 * Converts typed DsFile objects into .ds text output that Zoho Creator
 * can import via Settings > Import.
 *
 * Port of forgeds/core/build_ds.py emit functions to TypeScript.
 */

import type {
  DsApplication,
  DsBlueprint,
  DsFile,
  DsForm,
  DsFormWorkflow,
  DsMenuSection,
  DsPage,
  DsReport,
  DsSchedule,
} from "./ds-types";
import { TYPE_MAP, type DsFieldType } from "./ds-types";

// ============================================================
// Helpers
// ============================================================

const T = "\t";

function indent(depth: number): string {
  return T.repeat(depth);
}

/** Map forms.yaml field type to Zoho .ds type name. */
function zohoType(fieldType: DsFieldType): string {
  return TYPE_MAP[fieldType] ?? fieldType.toLowerCase();
}

/** Convert comma-separated choices to Zoho format: {"A","B","C"}. */
function formatChoices(choices: string): string {
  const items = choices
    .split(",")
    .map((c) => c.trim())
    .filter(Boolean);
  return "{" + items.map((i) => `"${i}"`).join(",") + "}";
}

/**
 * Re-indent Deluge code to the given tab depth.
 * Preserves relative indentation from the original source.
 */
function indentCode(code: string, depth: number): string {
  const lines = code.split("\n");
  const result: string[] = [];
  for (const line of lines) {
    const stripped = line.trim();
    if (!stripped) {
      result.push("");
    } else {
      const originalIndent = line.length - line.trimStart().length;
      const extraTabs = Math.floor(originalIndent / 4);
      result.push(indent(depth + extraTabs) + stripped);
    }
  }
  return result.join("\n");
}

function formatDate(): string {
  const now = new Date();
  const months = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
  ];
  const dd = String(now.getDate()).padStart(2, "0");
  const mmm = months[now.getMonth()];
  const yyyy = now.getFullYear();
  const hh = String(now.getHours()).padStart(2, "0");
  const mm = String(now.getMinutes()).padStart(2, "0");
  const ss = String(now.getSeconds()).padStart(2, "0");
  return `${dd}-${mmm}-${yyyy} ${hh}:${mm}:${ss}`;
}

// ============================================================
// Section emitters
// ============================================================

function emitHeader(app: DsApplication): string[] {
  const now = formatDate();
  return [
    "/*",
    " * Generated by : ForgeDS build-ds (TypeScript)",
    ` * Generated on : ${now}`,
    " * Version      : 1.0",
    " */",
    ` application "${app.displayName}"`,
    " {",
    `${indent(1)}date format = "${app.dateFormat}"`,
    `${indent(1)}time zone = "${app.timeZone}"`,
    `${indent(1)}time format = "${app.timeFormat}"`,
  ];
}

function emitForms(
  forms: DsForm[],
  blueprintForms: Map<string, string[]>,
): string[] {
  const lines: string[] = [];
  lines.push(`${indent(1)}forms`);
  lines.push(`\t{`);

  for (const form of forms) {
    lines.push(`\t\tform ${form.linkName}`);
    lines.push(`\t\t{`);
    lines.push(`\t\t\tdisplayname = "${form.displayName}"`);
    lines.push(`\t\t\tsuccess message = "${form.displayName} Added Successfully"`);

    // Section block (required by Zoho)
    lines.push(`\t\t\tSection`);
    lines.push(`\t\t\t(`);
    lines.push(`\t\t\t\ttype = section`);
    lines.push(`\t\t\t\trow = 1`);
    lines.push(`\t\t\t\tcolumn = 0   `);
    lines.push(`\t\t\t\twidth = medium`);
    lines.push(`\t\t\t)`);

    // Fields
    for (const fld of form.fields) {
      const prefix = fld.required ? "must have " : "";
      lines.push(`\t\t\t${prefix}${fld.name}`);
      lines.push(`\t\t\t(`);

      if (fld.fieldType === "Dropdown") {
        lines.push(`\t\t\t\ttype = picklist`);
        lines.push(`\t\t\t\tdisplayname = "${fld.displayName}"`);
        if (fld.choices) {
          lines.push(`\t\t\t\tvalues = ${formatChoices(fld.choices)}`);
        }
      } else {
        lines.push(`\t\t\t\ttype = ${zohoType(fld.fieldType)}`);
        lines.push(`\t\t\t\tdisplayname = "${fld.displayName}"`);
        if (fld.fieldType === "DateTime") {
          lines.push(`\t\t\t\ttimedisplayoptions = "hh:mm:ss"`);
          lines.push(`\t\t\t\talloweddays = 0,1,2,3,4,5,6`);
        } else if (fld.fieldType === "Date") {
          lines.push(`\t\t\t\talloweddays = 0,1,2,3,4,5,6`);
        } else if (fld.fieldType === "Checkbox") {
          lines.push(`\t\t\t\tinitial value = false`);
        } else if (fld.fieldType === "MultiLine") {
          lines.push(`\t\t\t\theight = 100px`);
        }
      }

      lines.push(`\t\t\t\trow = 1`);
      lines.push(`\t\t\t\tcolumn = 1   `);
      lines.push(`\t\t\t\twidth = medium`);
      lines.push(`\t\t\t)`);
    }

    // Actions block (required by Zoho)
    lines.push(`\t`);
    lines.push(`\t\t\tactions`);
    lines.push(`\t\t\t{`);
    lines.push(`\t\t\t\ton add`);
    lines.push(`\t\t\t\t{`);
    lines.push(`\t\t\t\t\tsubmit`);
    lines.push(`\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\ttype = submit`);
    lines.push(`\t\t\t\t\t\tdisplayname = "Submit"`);
    lines.push(`\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\treset`);
    lines.push(`\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\ttype = reset`);
    lines.push(`\t\t\t\t\t\tdisplayname = "Reset"`);
    lines.push(`\t\t\t\t\t)`);
    lines.push(`\t\t\t\t}`);
    lines.push(`\t\t\t\ton edit`);
    lines.push(`\t\t\t\t{`);
    lines.push(`\t\t\t\t\tupdate`);
    lines.push(`\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\ttype = submit`);
    lines.push(`\t\t\t\t\t\tdisplayname = "Update"`);
    lines.push(`\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\tcancel`);
    lines.push(`\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\ttype = cancel`);
    lines.push(`\t\t\t\t\t\tdisplayname = "Cancel"`);
    lines.push(`\t\t\t\t\t)`);
    lines.push(`\t\t\t\t}`);
    lines.push(`\t\t\t}`);

    // Blueprint components
    const bpStages = blueprintForms.get(form.linkName);
    if (bpStages) {
      lines.push(`\t\t\tblueprint components`);
      lines.push(`\t\t\t{`);
      const stageStr = bpStages.map((s) => `"${s}"`).join(",");
      lines.push(`\t\t\t\tstages = {${stageStr}}`);
      lines.push(`\t\t\t}`);
    }

    lines.push(`\t\t}`);
  }

  lines.push(`\t}`);
  return lines;
}

function emitReports(reports: DsReport[]): string[] {
  if (reports.length === 0) return [];

  const lines: string[] = [];
  lines.push(`\treports`);
  lines.push(`\t{`);

  for (const rpt of reports) {
    const cols = rpt.columns
      .split(",")
      .map((c) => c.trim())
      .filter(Boolean);

    lines.push(`\t\t${rpt.reportType} ${rpt.linkName}`);
    lines.push(`\t\t{`);
    lines.push(`\t\t\tdisplayName = "${rpt.linkName}"`);
    if (rpt.filter) {
      lines.push(`\t\t\tshow all rows from ${rpt.form}  [${rpt.filter}]  `);
    } else {
      lines.push(`\t\t\tshow all rows from ${rpt.form}    `);
    }
    lines.push(`\t\t\t(`);
    for (const c of cols) {
      lines.push(`\t\t\t\t${c} as "${c}"`);
    }
    lines.push(`\t\t\t)`);
    lines.push(`\t\t}`);
  }

  lines.push(`\t}`);
  return lines;
}

function emitPages(pages: DsPage[]): string[] {
  if (pages.length === 0) return [];

  const lines: string[] = [];
  lines.push(`\tpages`);
  lines.push(`\t{`);

  for (const page of pages) {
    lines.push(`\t\tpage ${page.linkName}`);
    lines.push(`\t\t{`);
    lines.push(`\t\t\tdisplayname = "${page.displayName}"`);
    lines.push(`\t\t\tContent="${page.content}"`);
    lines.push(`\t\t}`);
  }

  lines.push(`\t}`);
  return lines;
}

function emitBlueprints(blueprints: DsBlueprint[]): string[] {
  if (blueprints.length === 0) return [];

  const lines: string[] = [];
  lines.push(`\t\tblueprint`);
  lines.push(`\t\t{`);

  for (const bp of blueprints) {
    const stageDisplay = new Map(bp.stages.map((s) => [s.name, s.displayName]));

    lines.push(`    \t\t\t${bp.linkName} as "${bp.displayName}"`);
    lines.push(`    \t\t\t{`);
    lines.push(`        \t\t\ttype = Blueprint`);
    lines.push(`        \t\t\tform = ${bp.form}`);
    lines.push(`        \t\t\tstart`);
    lines.push(`        \t\t\t{`);
    if (bp.stages.length > 0) {
      lines.push(`            \t\t\tstart stage = "${bp.stages[0].displayName}"`);
    }
    lines.push(`        \t\t\t}`);
    lines.push(`        \t\t\tstages`);
    lines.push(`        \t\t\t{`);
    for (const stage of bp.stages) {
      lines.push(`           \t\t\t"${stage.displayName}"`);
      lines.push(`           \t\t\t{`);
      lines.push(`           \t\t\t}`);
    }
    lines.push(`        \t\t\t}`);
    lines.push(`        \t\t\ttransitions`);
    lines.push(`        \t\t\t{`);
    for (const t of bp.transitions) {
      const fromDisplay = stageDisplay.get(t.fromStage) ?? t.fromStage;
      const toDisplay = stageDisplay.get(t.toStage) ?? t.toStage;
      lines.push(`    \t\t\t\t${t.linkName} as "${t.displayName}"`);
      lines.push(`    \t\t\t\t{`);
      lines.push(`         \t\t\t\ttype = normal`);
      lines.push(`         \t\t\t\tfrom stage = "${fromDisplay}"`);
      lines.push(`         \t\t\t\tto stage = "${toDisplay}"`);
      lines.push(`         \t\t\t\tbefore`);
      lines.push(`         \t\t\t\t{`);
      lines.push(`         \t\t\t\t}`);
      lines.push(`         \t\t\t\tafter`);
      lines.push(`         \t\t\t\t{`);
      lines.push(`         \t\t\t\t}`);
      lines.push(`  \t\t\t\t}`);
    }
    lines.push(`        \t\t\t}`);
    lines.push(`    \t\t\t}`);
  }

  lines.push(`\t\t}`);
  return lines;
}

function emitWorkflow(
  workflows: DsFormWorkflow[],
  schedules: DsSchedule[],
  blueprints: DsBlueprint[],
  timeZone: string,
): string[] {
  if (workflows.length === 0 && schedules.length === 0 && blueprints.length === 0) {
    return [];
  }

  const lines: string[] = [];
  lines.push("");
  lines.push(`\t\tworkflow`);
  lines.push(`\t\t{`);

  if (workflows.length > 0) {
    lines.push(`\t\tform`);
    lines.push(`\t\t{`);
    for (const wf of workflows) {
      lines.push(`\t\t\t${wf.linkName} as "${wf.displayName}"`);
      lines.push(`\t\t\t{`);
      lines.push(`\t\t\t\ttype =  form`);
      lines.push(`\t\t\t\tform = ${wf.form}`);
      lines.push(``);
      lines.push(`\t\t\t\trecord event = ${wf.recordEvent}`);
      lines.push(``);
      lines.push(`\t\t\t\t${wf.eventType}`);
      lines.push(`\t\t\t\t{`);
      lines.push(`\t\t\t\t\tactions `);
      lines.push(`\t\t\t\t\t{`);
      lines.push(`\t\t\t\t\t\tcustom deluge script`);
      lines.push(`\t\t\t\t\t\t(`);
      lines.push(indentCode(wf.code, 7));
      lines.push(`\t\t\t\t\t\t)`);
      lines.push(`\t\t\t\t\t}`);
      lines.push(`\t\t\t\t}`);
      lines.push(``);
      lines.push(`\t\t\t}`);
    }
    lines.push(`\t\t}`);
  }

  if (schedules.length > 0) {
    lines.push(``);
    lines.push(`\t\tschedule`);
    lines.push(`\t\t{`);
    for (const sched of schedules) {
      lines.push(`\t\t\t${sched.linkName} as "${sched.displayName}"`);
      lines.push(`\t\t\t{`);
      lines.push(`\t\t\t\ttype =  schedule`);
      lines.push(`\t\t\t\tform = ${sched.form}`);
      lines.push(`\t\t\t\ttime zone = "${timeZone}"`);
      lines.push(`\t\t\t\ton start`);
      lines.push(`\t\t\t\t{`);
      lines.push(`\t\t\t\t\tactions `);
      lines.push(`\t\t\t\t\t{`);
      lines.push(`\t\t\t\t\ton load`);
      lines.push(`\t\t\t\t\t(`);
      lines.push(indentCode(sched.code, 6));
      lines.push(`\t\t\t\t\t)`);
      lines.push(`\t\t\t\t\t}`);
      lines.push(`\t\t\t\t}`);
      lines.push(`\t\t\t}`);
    }
    lines.push(`\t\t}`);
  }

  if (blueprints.length > 0) {
    lines.push(``);
    lines.push(``);
    lines.push(...emitBlueprints(blueprints));
  }

  lines.push(``);
  lines.push(``);
  lines.push(``);
  lines.push(`\t}`);
  return lines;
}

function emitShareSettings(roles: string[]): string[] {
  const lines: string[] = [];
  lines.push(`\tshare_settings`);
  lines.push(`\t{`);

  const profiles: Array<[string, string, string]> = [
    ["Read", "Users_Permissions", "This profile will have read permission for all components\\n"],
    ["Write", "Users_Permissions", "This profile will have write permission for all components\\n"],
    ["Administrator", "Users_Permissions", "This profile will have all the permissions.\\n"],
    ["Developer", "Developer", "Developer Profile\\n"],
    ["Customer", "Customer_Portal", "This is the default profile having only add and view permission.\\n"],
  ];

  for (const [name, type, desc] of profiles) {
    lines.push(`\t\t\t"${name}"`);
    lines.push(`\t\t\t{`);
    lines.push(`\t\t\t\tname = "${name}"`);
    lines.push(`\t\t\t\ttype = ${type}`);
    lines.push(`\t\t\t\tpermissions = {Chat:true, Predefined:true, ApiAccess:true, PIIAccess:true, ePHIAccess:true}`);
    lines.push(`\t\t\t\tdescription = "${desc}"`);
    lines.push(`\t\t\t}`);
  }

  lines.push(`\t\t\troles`);
  lines.push(`\t\t\t{`);
  const roleList = roles.length > 0 ? roles : ["CEO"];
  for (const role of roleList) {
    lines.push(`\t\t\t\t"${role}"`);
    lines.push(`\t\t\t\t{`);
    lines.push(`\t\t\t\t\tdescription = "User belonging to this role can access data of all other users."`);
    lines.push(`\t\t\t\t}`);
  }
  lines.push(`\t\t\t}`);
  lines.push(`\t}`);
  return lines;
}

function emitWebReports(reports: DsReport[]): string[] {
  if (reports.length === 0) return [];

  const lines: string[] = [];
  lines.push(`\t\treports`);
  lines.push(`\t\t{`);

  for (const rpt of reports) {
    const cols = rpt.columns
      .split(",")
      .map((c) => c.trim())
      .filter(Boolean);

    lines.push(`\t\t\treport ${rpt.linkName}`);
    lines.push(`\t\t\t{`);

    // Quickview
    lines.push(`\t\t\t\tquickview`);
    lines.push(`\t\t\t\t(`);
    lines.push(`\t\t\t\t\tlayout`);
    lines.push(`\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\ttype = -1`);
    lines.push(`\t\t\t\t\t\tdatablock1`);
    lines.push(`\t\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\t\tlayout type = -1`);
    lines.push(`\t\t\t\t\t\t\tfields`);
    lines.push(`\t\t\t\t\t\t\t(`);
    for (const c of cols) {
      lines.push(`\t\t\t\t\t\t\t\t${c} as "${c}"`);
    }
    lines.push(`\t\t\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\tmenu`);
    lines.push(`\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\theader`);
    lines.push(`\t\t\t\t\t\t(`);
    for (const item of ["Edit ", "Duplicate ", "Delete ", "Print ", "Add ", "Import ", "Export "]) {
      lines.push(`\t\t\t\t\t\t\t${item}`);
    }
    lines.push(`\t\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\t\trecord`);
    lines.push(`\t\t\t\t\t\t(`);
    for (const item of ["Edit", "Duplicate", "Delete", "Print"]) {
      lines.push(`\t\t\t\t\t\t\t${item}   \t   `);
    }
    lines.push(`\t\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\taction`);
    lines.push(`\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\ton click`);
    lines.push(`\t\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\t\tView Record   \t   `);
    lines.push(`\t\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\t\ton right click`);
    lines.push(`\t\t\t\t\t\t(`);
    for (const item of ["Edit", "Duplicate", "Delete", "Print", "View Record"]) {
      lines.push(`\t\t\t\t\t\t\t${item}   \t   `);
    }
    lines.push(`\t\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\t)`);
    lines.push(`\t\t\t\t)`);
    lines.push(``);

    // Detailview
    lines.push(`\t\t\t\tdetailview`);
    lines.push(`\t\t\t\t(`);
    lines.push(`\t\t\t\t\tlayout`);
    lines.push(`\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\ttype = 1`);
    lines.push(`\t\t\t\t\t\tdatablock1`);
    lines.push(`\t\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\t\tlayout type = -2`);
    lines.push(`\t\t\t\t\t\t\ttitle = "Overview"`);
    lines.push(`\t\t\t\t\t\t\tfields`);
    lines.push(`\t\t\t\t\t\t\t(`);
    for (const c of cols) {
      lines.push(`\t\t\t\t\t\t\t\t${c} as "${c}"`);
    }
    lines.push(`\t\t\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\tmenu`);
    lines.push(`\t\t\t\t\t(`);
    lines.push(`\t\t\t\t\t\theader`);
    lines.push(`\t\t\t\t\t\t(`);
    for (const item of ["Edit ", "Duplicate ", "Delete ", "Print "]) {
      lines.push(`\t\t\t\t\t\t\t${item}`);
    }
    lines.push(`\t\t\t\t\t\t)`);
    lines.push(`\t\t\t\t\t)`);
    lines.push(`\t\t\t\t)`);

    lines.push(`\t\t\t}`);
  }

  lines.push(`\t\t}`);
  return lines;
}

function emitWeb(
  forms: DsForm[],
  reports: DsReport[],
  menuSections: DsMenuSection[],
  pages: DsPage[],
): string[] {
  const lines: string[] = [];
  lines.push(`\tweb`);
  lines.push(`\t{`);

  // Web > forms
  lines.push(`\t\tforms`);
  lines.push(`\t\t{`);
  for (const form of forms) {
    lines.push(`\t\t\tform ${form.linkName}`);
    lines.push(`\t\t\t{`);
    lines.push(`\t\t\t\tlabel placement = left`);
    lines.push(`\t\t\t}`);
  }
  lines.push(`\t\t}`);

  // Web > reports
  lines.push(...emitWebReports(reports));

  // Web > menu
  lines.push(`\t\tmenu`);
  lines.push(`\t\t{`);
  lines.push(`\t\t\tspace Space`);
  lines.push(`\t\t\t{`);
  lines.push(`\t\t\t\tdisplayname = "Space"`);
  lines.push(`\t\t\t\ticon = "objects-spaceship"`);

  // Group reports by form
  const formReports = new Map<string, DsReport[]>();
  for (const rpt of reports) {
    const existing = formReports.get(rpt.form) ?? [];
    existing.push(rpt);
    formReports.set(rpt.form, existing);
  }

  let sectionNum = 0;

  // Dashboard page section
  if (pages.length > 0) {
    sectionNum += 1;
    lines.push(``);
    lines.push(`\t\t\t\tsection Section_${sectionNum}`);
    lines.push(`\t\t\t\t{`);
    lines.push(`\t\t\t\t\tdisplayname = "Dashboard"`);
    lines.push(`\t\t\t\t\ticon = "ui-1-dashboard-half"`);
    lines.push(`\t\t\t\t\tpage DashBoard`);
    lines.push(`\t\t\t\t\t{`);
    lines.push(`\t\t\t\t\t\ticon = "ui-1-dashboard-half"`);
    lines.push(`\t\t\t\t\t}`);
    lines.push(`\t\t\t\t}`);
  }

  // Menu sections from config or auto-generated per form
  if (menuSections.length > 0) {
    for (const section of menuSections) {
      sectionNum += 1;
      lines.push(``);
      lines.push(`\t\t\t\tsection Section_${sectionNum}`);
      lines.push(`\t\t\t\t{`);
      lines.push(`\t\t\t\t\tdisplayname = "${section.displayName}"`);
      lines.push(`\t\t\t\t\ticon = "${section.icon}"`);
      for (const f of section.forms ?? []) {
        lines.push(`\t\t\t\t\tform  ${f}`);
        lines.push(`\t\t\t\t\t{`);
        lines.push(`\t\t\t\t\t\ticon = "ui-1-bold-add"`);
        lines.push(`\t\t\t\t\t}`);
      }
      for (const r of section.reports ?? []) {
        lines.push(`\t\t\t\t\treport ${r}`);
        lines.push(`\t\t\t\t\t{`);
        lines.push(`\t\t\t\t\t\ticon = "travel-world"`);
        lines.push(`\t\t\t\t\t}`);
      }
      for (const p of section.pages ?? []) {
        lines.push(`\t\t\t\t\tpage ${p}`);
        lines.push(`\t\t\t\t\t{`);
        lines.push(`\t\t\t\t\t\ticon = "ui-1-dashboard-half"`);
        lines.push(`\t\t\t\t\t}`);
      }
      lines.push(`\t\t\t\t}`);
    }
  } else {
    // Auto-generate per form
    for (const form of forms) {
      sectionNum += 1;
      lines.push(``);
      lines.push(`\t\t\t\tsection Section_${sectionNum}`);
      lines.push(`\t\t\t\t{`);
      lines.push(`\t\t\t\t\tdisplayname = "${form.displayName}"`);
      lines.push(`\t\t\t\t\ticon = "travel-world"`);
      lines.push(`\t\t\t\t\tform  ${form.linkName}`);
      lines.push(`\t\t\t\t\t{`);
      lines.push(`\t\t\t\t\t\ticon = "ui-1-bold-add"`);
      lines.push(`\t\t\t\t\t}`);
      for (const rpt of formReports.get(form.linkName) ?? []) {
        lines.push(`\t\t\t\t\treport ${rpt.linkName}`);
        lines.push(`\t\t\t\t\t{`);
        lines.push(`\t\t\t\t\t\ticon = "travel-world"`);
        lines.push(`\t\t\t\t\t}`);
      }
      lines.push(`\t\t\t\t}`);
    }
  }

  lines.push(`\t\t\t}`);

  // menu > preference
  lines.push(`\t\t\tpreference`);
  lines.push(`\t\t\t{`);
  lines.push(`\t\t\t\ticon`);
  lines.push(`\t\t\t\t{`);
  lines.push(`\t\t\t\t\tstyle = solid`);
  lines.push(`\t\t\t\t\tshow = {space,section,component}`);
  lines.push(`\t\t\t\t}`);
  lines.push(`\t\t\t}`);
  lines.push(`\t\t}`);

  // web > customize
  lines.push(`\t\tcustomize`);
  lines.push(`\t\t{`);
  lines.push(`\t\t\tnew theme = 11`);
  lines.push(`\t\t\tfont = "poppins"`);
  lines.push(`\t\t\tcolor options`);
  lines.push(`\t\t\t{`);
  lines.push(`\t\t\t\tcolor = "5"`);
  lines.push(`\t\t\t}`);
  lines.push(`\t\t\tlogo`);
  lines.push(`\t\t\t{`);
  lines.push(`\t\t\t\tpreference = "none"`);
  lines.push(`\t\t\t\tplacement = "left"`);
  lines.push(`\t\t\t}`);
  lines.push(`\t\t}`);
  lines.push(`\t}`);
  return lines;
}

function emitDevice(forms: DsForm[], deviceName: string): string[] {
  const lines: string[] = [];
  lines.push(`\t${deviceName}`);
  lines.push(`\t{`);
  lines.push(`\t\tforms`);
  lines.push(`\t\t{`);
  for (const form of forms) {
    lines.push(`\t\t\tform ${form.linkName}`);
    lines.push(`\t\t\t{`);
    lines.push(`\t\t\t\tlabel placement = auto`);
    lines.push(`\t\t\t}`);
  }
  lines.push(`\t\t}`);
  lines.push(`\t\tcustomize`);
  lines.push(`\t\t{`);
  lines.push(`\t\t\tlayout = slidingpane`);
  lines.push(`\t\t\tfont = "default"`);
  lines.push(`\t\t\tstyle = "3"`);
  lines.push(`\t\t\tcolor options`);
  lines.push(`\t\t\t{`);
  lines.push(`\t\t\t\tcolor = green`);
  lines.push(`\t\t\t}`);
  lines.push(`\t\t\tlogo`);
  lines.push(`\t\t\t{`);
  lines.push(`\t\t\t\tpreference = "none"`);
  lines.push(`\t\t\t}`);
  lines.push(`\t\t}`);
  lines.push(`\t}`);
  return lines;
}

function emitTranslation(): string[] {
  return [
    `\ttranslation`,
    `{`,
    `{"Language_Settings":{"LANGAGUE_WITH_LOGIN":"browser"}}`,
    `}`,
  ];
}

// ============================================================
// Main emitter
// ============================================================

/**
 * Generate a complete Zoho Creator .ds file from a typed DsFile object.
 *
 * The output matches the format produced by `forgeds-build-ds` (Python)
 * and can be imported into Zoho Creator via Settings > Import.
 */
export function emitDs(file: DsFile): string {
  const lines: string[] = [];

  // Header + application declaration
  lines.push(...emitHeader(file.application));

  // Build blueprint_forms map
  const blueprintForms = new Map<string, string[]>();
  for (const bp of file.blueprints) {
    blueprintForms.set(bp.form, bp.stages.map((s) => s.displayName));
  }

  // Forms
  lines.push("");
  lines.push(...emitForms(file.forms, blueprintForms));

  // Reports
  if (file.reports.length > 0) {
    lines.push("");
    lines.push(...emitReports(file.reports));
  }

  // Pages
  if (file.pages.length > 0) {
    lines.push("");
    lines.push(...emitPages(file.pages));
  }

  // Workflow (form workflows + schedules + blueprints)
  lines.push(
    ...emitWorkflow(
      file.workflows,
      file.schedules,
      file.blueprints,
      file.application.timeZone,
    ),
  );

  // Share settings
  lines.push(...emitShareSettings(file.roles));

  // Web section
  lines.push(...emitWeb(file.forms, file.reports, file.menuSections, file.pages));

  // Phone & tablet
  lines.push(...emitDevice(file.forms, "phone"));
  lines.push(...emitDevice(file.forms, "tablet"));

  // Translation
  lines.push(...emitTranslation());

  // Close application block
  lines.push("}");

  return lines.join("\n") + "\n";
}
