"""Tests for gen_sdk_mock.py generator (Phase 2B Task 2)."""

from __future__ import annotations

import json
import os
import shutil
import sqlite3
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))


REPO_ROOT = Path(__file__).resolve().parent.parent
RUNTIME_DIR = REPO_ROOT / "src" / "forgeds" / "widgets" / "runtime"
SDK_MOCK = RUNTIME_DIR / "sdk_mock.js"
DB_PATH = REPO_ROOT / "zoho_widget_sdk.db"


def _node_available() -> bool:
    return shutil.which("node") is not None


def _regenerate() -> None:
    r = subprocess.run(
        [sys.executable, "-m", "forgeds.widgets.gen_sdk_mock"],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
    )
    assert r.returncode == 0, f"gen_sdk_mock failed: {r.stderr}"


@pytest.fixture(scope="module", autouse=True)
def _ensure_db_built():
    if not DB_PATH.exists():
        r = subprocess.run(
            [sys.executable, "-m", "forgeds.widgets.build_widget_sdk_db"],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
        )
        assert r.returncode == 0, f"build_widget_sdk_db failed: {r.stderr}"
    return DB_PATH


def test_generator_writes_file():
    _regenerate()
    assert SDK_MOCK.exists()


def test_generator_emits_banner_comment():
    _regenerate()
    first_line = SDK_MOCK.read_text(encoding="utf-8").splitlines()[0]
    assert first_line.startswith("// GENERATED by gen_sdk_mock.py")


def test_generator_is_deterministic():
    _regenerate()
    a = SDK_MOCK.read_bytes()
    _regenerate()
    b = SDK_MOCK.read_bytes()
    assert a == b


def test_generator_covers_all_seeded_namespaces():
    _regenerate()
    conn = sqlite3.connect(str(DB_PATH))
    try:
        rows = conn.execute("SELECT name FROM sdk_namespaces").fetchall()
    finally:
        conn.close()
    text = SDK_MOCK.read_text(encoding="utf-8")
    for (ns_name,) in rows:
        assert ns_name in text, f"namespace {ns_name!r} missing from sdk_mock.js"


@pytest.mark.skipif(not _node_available(), reason="Node not on PATH")
def test_sdk_mock_covers_all_seeded_apis():
    _regenerate()
    conn = sqlite3.connect(str(DB_PATH))
    try:
        methods = conn.execute(
            "SELECT namespace, name FROM sdk_methods ORDER BY namespace, name"
        ).fetchall()
    finally:
        conn.close()

    enumerate_js = (
        "const {ZOHO} = require('./sdk_mock.js');"
        "function walk(o,p,out){if(!o||typeof o!=='object')return;"
        "for(const k of Object.keys(o)){"
        "if(k.startsWith('_'))continue;"
        "const v=o[k];const q=p+'.'+k;"
        "if(typeof v==='function')out.push(q);"
        "else if(v&&typeof v==='object')walk(v,q,out);}}"
        "const r=[];walk(ZOHO,'ZOHO',r);console.log(JSON.stringify(r));"
    )
    r = subprocess.run(
        ["node", "-e", enumerate_js],
        cwd=str(RUNTIME_DIR),
        capture_output=True,
        text=True,
    )
    assert r.returncode == 0, f"node enum failed: {r.stderr}"
    reached = set(json.loads(r.stdout.strip()))
    for ns, name in methods:
        expected = f"{ns}.{name}"
        assert expected in reached, f"{expected} not reachable in sdk_mock.js"


@pytest.mark.skipif(not _node_available(), reason="Node not on PATH")
def test_generated_mock_logs_calls_to_call_log():
    _regenerate()
    js = (
        "const {ZOHO} = require('./sdk_mock.js');"
        "Promise.resolve(ZOHO.CREATOR.API.getRecords('r', '', 1, 10))"
        ".then(()=>{process.stdout.write(JSON.stringify(ZOHO._callLog));});"
    )
    r = subprocess.run(
        ["node", "-e", js], cwd=str(RUNTIME_DIR), capture_output=True, text=True
    )
    assert r.returncode == 0, r.stderr
    log = json.loads(r.stdout.strip())
    assert len(log) == 1
    assert log[0]["method"] == "ZOHO.CREATOR.API.getRecords"
    assert log[0]["responseKind"] == "canned"
    assert log[0]["args"] == ["r", "", 1, 10]


@pytest.mark.skipif(not _node_available(), reason="Node not on PATH")
def test_generated_mock_unknown_method_falls_through_proxy():
    _regenerate()
    js = (
        "const {ZOHO} = require('./sdk_mock.js');"
        "const r = ZOHO.CREATOR.API.madeUpMethod('x');"
        "process.stdout.write(JSON.stringify({"
        "result: r === undefined,"
        "log: ZOHO._callLog"
        "}));"
    )
    r = subprocess.run(
        ["node", "-e", js], cwd=str(RUNTIME_DIR), capture_output=True, text=True
    )
    assert r.returncode == 0, r.stderr
    out = json.loads(r.stdout.strip())
    assert out["result"] is True
    assert len(out["log"]) == 1
    assert out["log"][0]["responseKind"] == "undeclared-method"
    assert out["log"][0]["method"] == "ZOHO.CREATOR.API.madeUpMethod"


@pytest.mark.skipif(not _node_available(), reason="Node not on PATH")
def test_generated_mock_records_permissions_on_write():
    _regenerate()
    js = (
        "const {ZOHO} = require('./sdk_mock.js');"
        "Promise.resolve(ZOHO.CREATOR.API.addRecords('form', {}))"
        ".then(()=>{process.stdout.write(JSON.stringify(ZOHO._permissionsObserved));});"
    )
    r = subprocess.run(
        ["node", "-e", js], cwd=str(RUNTIME_DIR), capture_output=True, text=True
    )
    assert r.returncode == 0, r.stderr
    perms = json.loads(r.stdout.strip())
    assert "ZOHO.CREATOR.API.write" in perms
