// GENERATED by gen_sdk_mock.py — do not edit
'use strict';

const __start = Date.now();
const _callLog = [];
const _permissionsObserved = [];

function _safeArgs(args) {
  const arr = Array.from(args);
  try { return JSON.parse(JSON.stringify(arr)); }
  catch (e) {
    return arr.map(a => {
      try { return JSON.parse(JSON.stringify(a)); }
      catch (_) { return '__nonserialisable__'; }
    });
  }
}

function _record(method, args, responseKind, permissions) {
  if (permissions) {
    for (const p of permissions) {
      if (!_permissionsObserved.includes(p)) _permissionsObserved.push(p);
    }
  }
  _callLog.push({
    method,
    args: _safeArgs(args),
    responseKind,
    timestamp: Date.now() - __start,
  });
}

function _wrapNs(nsPath, impl) {
  return new Proxy(impl, {
    get(target, prop) {
      if (prop in target) return target[prop];
      if (typeof prop !== 'string') return undefined;
      return function() {
        _record(nsPath + '.' + prop, arguments, 'undeclared-method', null);
        return undefined;
      };
    }
  });
}

const _impl_ZOHO_CREATOR_API = {
  addRecords: function() {
    _record("ZOHO.CREATOR.API.addRecords", arguments, 'canned', ["ZOHO.CREATOR.API.write"]);
    return Promise.resolve({ code: 3000, data: { ID: "0" } });
  },
  bulkUpdateRecords: function() {
    _record("ZOHO.CREATOR.API.bulkUpdateRecords", arguments, 'canned', ["ZOHO.CREATOR.API.write"]);
    return Promise.resolve({ code: 3000, data: { ID: "0" } });
  },
  callFunction: function() {
    _record("ZOHO.CREATOR.API.callFunction", arguments, 'canned', ["ZOHO.CREATOR.API.read"]);
    return Promise.resolve({ code: 0, data: null });
  },
  deleteRecord: function() {
    _record("ZOHO.CREATOR.API.deleteRecord", arguments, 'canned', ["ZOHO.CREATOR.API.write"]);
    return Promise.resolve({ code: 3000, data: { ID: "0" } });
  },
  downloadFile: function() {
    _record("ZOHO.CREATOR.API.downloadFile", arguments, 'canned', ["ZOHO.CREATOR.API.read"]);
    return Promise.resolve({ code: 3000, data: { file_id: "0" } });
  },
  getFileContent: function() {
    _record("ZOHO.CREATOR.API.getFileContent", arguments, 'canned', ["ZOHO.CREATOR.API.read"]);
    return Promise.resolve({ code: 3000, data: [] });
  },
  getRecordById: function() {
    _record("ZOHO.CREATOR.API.getRecordById", arguments, 'canned', ["ZOHO.CREATOR.API.read"]);
    return Promise.resolve({ code: 3000, data: [] });
  },
  getRecords: function() {
    _record("ZOHO.CREATOR.API.getRecords", arguments, 'canned', ["ZOHO.CREATOR.API.read"]);
    return Promise.resolve({ code: 3000, data: [] });
  },
  invokeApi: function() {
    _record("ZOHO.CREATOR.API.invokeApi", arguments, 'canned', ["ZOHO.CREATOR.API.read"]);
    return Promise.resolve({ code: 0, data: null });
  },
  invokeConnection: function() {
    _record("ZOHO.CREATOR.API.invokeConnection", arguments, 'canned', ["ZOHO.CREATOR.API.read"]);
    return Promise.resolve({ code: 0, data: null });
  },
  invokeCustomApi: function() {
    _record("ZOHO.CREATOR.API.invokeCustomApi", arguments, 'canned', ["ZOHO.CREATOR.API.read"]);
    return Promise.resolve({ code: 0, data: null });
  },
  updateRecord: function() {
    _record("ZOHO.CREATOR.API.updateRecord", arguments, 'canned', ["ZOHO.CREATOR.API.write"]);
    return Promise.resolve({ code: 3000, data: { ID: "0" } });
  },
  uploadFile: function() {
    _record("ZOHO.CREATOR.API.uploadFile", arguments, 'canned', ["ZOHO.CREATOR.API.write"]);
    return Promise.resolve({ code: 3000, data: { file_id: "0" } });
  },
};

const _impl_ZOHO_CREATOR_PUBLISH = {
  publish: function() {
    _record("ZOHO.CREATOR.PUBLISH.publish", arguments, 'canned', ["ZOHO.CREATOR.API.publish"]);
    return Promise.resolve({ code: 3000 });
  },
  unpublish: function() {
    _record("ZOHO.CREATOR.PUBLISH.unpublish", arguments, 'canned', ["ZOHO.CREATOR.API.publish"]);
    return Promise.resolve({ code: 3000 });
  },
};

const _impl_ZOHO_CREATOR_UTIL = {
  closeWidget: function() {
    _record("ZOHO.CREATOR.UTIL.closeWidget", arguments, 'canned', null);
    return undefined;
  },
  navigateTo: function() {
    _record("ZOHO.CREATOR.UTIL.navigateTo", arguments, 'canned', null);
    return undefined;
  },
  showAlert: function() {
    _record("ZOHO.CREATOR.UTIL.showAlert", arguments, 'canned', null);
    return undefined;
  },
  showPrompt: function() {
    _record("ZOHO.CREATOR.UTIL.showPrompt", arguments, 'canned', null);
    return undefined;
  },
};

const _impl_ZOHO_embeddedApp = {
  getInitParams: function() {
    _record("ZOHO.embeddedApp.getInitParams", arguments, 'canned', null);
    return Promise.resolve({ appLinkName: "mock", loginName: "mock" });
  },
  getUserInfo: function() {
    _record("ZOHO.embeddedApp.getUserInfo", arguments, 'canned', null);
    return Promise.resolve({ appLinkName: "mock", loginName: "mock" });
  },
  init: function() {
    _record("ZOHO.embeddedApp.init", arguments, 'canned', null);
    return Promise.resolve();
  },
  logout: function() {
    _record("ZOHO.embeddedApp.logout", arguments, 'canned', null);
    return Promise.resolve();
  },
  on: function() {
    _record("ZOHO.embeddedApp.on", arguments, 'canned', null);
    return undefined;
  },
};

const ZOHO = {};
ZOHO.CREATOR = ZOHO.CREATOR || {};
ZOHO.CREATOR.API = _wrapNs("ZOHO.CREATOR.API", _impl_ZOHO_CREATOR_API);
ZOHO.CREATOR.PUBLISH = _wrapNs("ZOHO.CREATOR.PUBLISH", _impl_ZOHO_CREATOR_PUBLISH);
ZOHO.CREATOR.UTIL = _wrapNs("ZOHO.CREATOR.UTIL", _impl_ZOHO_CREATOR_UTIL);
ZOHO.embeddedApp = _wrapNs("ZOHO.embeddedApp", _impl_ZOHO_embeddedApp);

ZOHO._callLog = _callLog;
ZOHO._permissionsObserved = _permissionsObserved;

module.exports = { ZOHO };
