"""Generate src/forgeds/widgets/runtime/sdk_mock.js from zoho_widget_sdk.db.

Phase 2B harness-mock generator. Stdlib-only. Idempotent: byte-identical
output for a given DB state, so the committed `sdk_mock.js` reviews cleanly.

Regeneration (two-step, per spec §5.1):

    forgeds-build-widget-db
    python -m forgeds.widgets.gen_sdk_mock

The generated file is committed alongside the generator — `forgeds-run-widget`
does NOT regenerate at invocation time.
"""

from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

from forgeds._shared.config import get_db_dir

BANNER = "// GENERATED by gen_sdk_mock.py — do not edit\n"
OUT_PATH = Path(__file__).parent / "runtime" / "sdk_mock.js"
DB_NAME = "zoho_widget_sdk.db"


_RESPONSE_TABLE = {
    "getRecords": "Promise.resolve({ code: 3000, data: [] })",
    "getRecordById": "Promise.resolve({ code: 3000, data: [] })",
    "getFileContent": "Promise.resolve({ code: 3000, data: [] })",
    "downloadFile": 'Promise.resolve({ code: 3000, data: { file_id: "0" } })',
    "uploadFile": 'Promise.resolve({ code: 3000, data: { file_id: "0" } })',
    "addRecords": 'Promise.resolve({ code: 3000, data: { ID: "0" } })',
    "updateRecord": 'Promise.resolve({ code: 3000, data: { ID: "0" } })',
    "deleteRecord": 'Promise.resolve({ code: 3000, data: { ID: "0" } })',
    "bulkUpdateRecords": 'Promise.resolve({ code: 3000, data: { ID: "0" } })',
    "invokeCustomApi": "Promise.resolve({ code: 0, data: null })",
    "invokeApi": "Promise.resolve({ code: 0, data: null })",
    "invokeConnection": "Promise.resolve({ code: 0, data: null })",
    "callFunction": "Promise.resolve({ code: 0, data: null })",
    "getInitParams": 'Promise.resolve({ appLinkName: "mock", loginName: "mock" })',
    "getUserInfo": 'Promise.resolve({ appLinkName: "mock", loginName: "mock" })',
    "showAlert": "undefined",
    "showPrompt": "undefined",
    "navigateTo": "undefined",
    "closeWidget": "undefined",
    "init": "Promise.resolve()",
    "logout": "Promise.resolve()",
    "on": "undefined",
    "publish": "Promise.resolve({ code: 3000 })",
    "unpublish": "Promise.resolve({ code: 3000 })",
}


def _canned_response_js(name: str) -> str:
    return _RESPONSE_TABLE.get(name, "Promise.resolve({ code: 3000 })")


def _js_string_literal(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _ns_var(ns: str) -> str:
    return "_impl_" + ns.replace(".", "_")


def _perms_js(perms: str | None) -> str:
    if not perms:
        return "null"
    parts = [p.strip() for p in perms.split(",") if p.strip()]
    return "[" + ", ".join(_js_string_literal(p) for p in parts) + "]"


_PRELUDE = """'use strict';

const __start = Date.now();
const _callLog = [];
const _permissionsObserved = [];

function _safeArgs(args) {
  const arr = Array.from(args);
  try { return JSON.parse(JSON.stringify(arr)); }
  catch (e) {
    return arr.map(a => {
      try { return JSON.parse(JSON.stringify(a)); }
      catch (_) { return '__nonserialisable__'; }
    });
  }
}

function _record(method, args, responseKind, permissions) {
  if (permissions) {
    for (const p of permissions) {
      if (!_permissionsObserved.includes(p)) _permissionsObserved.push(p);
    }
  }
  _callLog.push({
    method,
    args: _safeArgs(args),
    responseKind,
    timestamp: Date.now() - __start,
  });
}

function _wrapNs(nsPath, impl) {
  return new Proxy(impl, {
    get(target, prop) {
      if (prop in target) return target[prop];
      if (typeof prop !== 'string') return undefined;
      return function() {
        _record(nsPath + '.' + prop, arguments, 'undeclared-method', null);
        return undefined;
      };
    }
  });
}

"""


def build_mock(db_path: Path) -> str:
    """Return the full sdk_mock.js source as a string."""
    conn = sqlite3.connect(str(db_path))
    try:
        rows = conn.execute(
            "SELECT namespace, name, required_permissions "
            "FROM sdk_methods ORDER BY namespace, name"
        ).fetchall()
    finally:
        conn.close()

    by_ns: dict[str, list[tuple[str, str | None]]] = {}
    for ns, name, perms in rows:
        by_ns.setdefault(ns, []).append((name, perms))

    out: list[str] = [BANNER, _PRELUDE]

    for ns in sorted(by_ns.keys()):
        out.append(f"const {_ns_var(ns)} = {{\n")
        for name, perms in by_ns[ns]:
            path = f"{ns}.{name}"
            out.append(
                f"  {name}: function() {{\n"
                f"    _record({_js_string_literal(path)}, arguments, "
                f"'canned', {_perms_js(perms)});\n"
                f"    return {_canned_response_js(name)};\n"
                f"  }},\n"
            )
        out.append("};\n\n")

    out.append("const ZOHO = {};\n")
    emitted_intermediates: set[str] = set()
    for ns in sorted(by_ns.keys()):
        parts = ns.split(".")
        if parts[0] != "ZOHO":
            continue
        for i in range(1, len(parts) - 1):
            intermediate = ".".join(parts[: i + 1])
            if intermediate not in emitted_intermediates:
                out.append(f"{intermediate} = {intermediate} || {{}};\n")
                emitted_intermediates.add(intermediate)
        leaf = ".".join(parts)
        out.append(
            f"{leaf} = _wrapNs({_js_string_literal(ns)}, {_ns_var(ns)});\n"
        )

    out.append(
        "\n"
        "ZOHO._callLog = _callLog;\n"
        "ZOHO._permissionsObserved = _permissionsObserved;\n\n"
        "module.exports = { ZOHO };\n"
    )

    return "".join(out)


def main() -> int:
    """CLI entry: write sdk_mock.js. Exit 1 if DB missing."""
    db = get_db_dir() / DB_NAME
    if not db.exists():
        print(f"error: {DB_NAME} not found at {db}", file=sys.stderr)
        print("       run: forgeds-build-widget-db", file=sys.stderr)
        return 1
    text = build_mock(db)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
